[package]
name = "pattern"
version = "1.0.0"
edition = "2021"

[dependencies]
bevy = { version = "0.13.2" }
terminal = { git = "https://github.com/ka-de/terminal" }
perf_ui = { git = "https://github.com/ka-de/perf_ui" }
rand = "0.8.5"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
bevy = { version = "0.13.2", features = ["dynamic_linking"] }

[workspace]
resolver = "2"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
