[package]
name = "pattern"
version = "1.0.0"
edition = "2021"

[build-dependencies]
embed-resource = "2.4.2"

[dependencies]
perf_ui = { git = "https://github.com/ka-de/perf_ui" }
bevy_ecs_ldtk = { git = "https://github.com/ka-de/bevy_ecs_ldtk" }
bevy-inspector-egui = { git = "https://github.com/ka-de/bevy-inspector-egui" }
bevy_tweening = { git = "https://github.com/ka-de/bevy_tweening" }
#bevy_framepace = { git = "https://github.com/ka-de/bevy_framepace" }
#bevy_smooth_pixel_camera = { git = "https://github.com/ka-de/bevy_smooth_pixel_camera" }
bevy_progress = { git = "https://github.com/ka-de/bevy_progress", features = [
  "assets",
  "debug",
] }
bevy-steamworks = { git = "https://github.com/ka-de/bevy_steamworks", features = [
  "serde",
] }
rand = "0.8.5"
bevy_rapier2d = { version = "0.26.0", features = ["simd-stable"] }
sickle_ui = { git = "https://github.com/ka-de/sickle_ui" }
bevy_yarnspinner = { git = "https://github.com/ka-de/YarnSpinner-Rust" }
bevy_yarnspinner_example_dialogue_view = { git = "https://github.com/ka-de/YarnSpinner-Rust" }
wgpu = { version = "0.19.3", default-features = false, features = [
  "wgsl",
  "dx12",
  "metal",
  "naga",
  "naga-ir",
  "fragile-send-sync-non-atomic-wasm",
] }

# Only enable dynamic linking in `sickle_ui` when not building wasm32.
[target.'cfg(not(target_arch = "wasm32"))'.dependencies.sickle_ui]
git = "https://github.com/ka-de/sickle_ui"
features = ["dev"]

[dependencies.bevy]
version = "0.13.2"
default-features = false
features = [
  "png",
  "vorbis",
  "animation",
  "bevy_audio",
  "bevy_gilrs",           # gamepad support
  "bevy_gizmos",
  "bevy_sprite",
  "bevy_animation",
  "bevy_ui",
  "bevy_text",
  "subpixel_glyph_atlas",
  "bevy_render",
]

[dependencies.bevy_asset_loader]
git = "https://github.com/ka-de/bevy_asset_loader"
default-features = false
features = ["2d", "standard_dynamic_assets", "progress_tracking"]

# Only enable `webgpu` on wasm32
[target.'cfg(target_arch = "wasm32")'.dependencies.bevy]
version = "0.13.2"
features = ["webgpu"]

# Only enable dynamic linking when not building wasm32.
[target.'cfg(not(target_arch = "wasm32"))'.dependencies.bevy]
version = "0.13.2"
features = [
  "dynamic_linking",
  "multi-threaded",
  "file_watcher",
  "bevy_winit",
  "embedded_watcher",
]

[workspace]
resolver = "2"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
