name: Rust

on:
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]

env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Cargo Cache
              uses: actions/cache@v4
              with:
                  path: |
                      ~/.cargo/registry
                      ~/.cargo/git
                      target
                  key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}
                  restore-keys: |
                      ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}
                      ${{ runner.os }}-cargo
            - name: Install dependencies
              run: sudo apt-get install -y clang pkg-config libx11-dev libasound2-dev libudev-dev libxkbcommon-x11-0 libwayland-dev libxkbcommon-dev libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev mesa-vulkan-drivers
            - name: Cargo Update
              run: cargo update --verbose
            - name: Build Debug
              run: cargo build --features "bevy/dynamic_linking" --verbose
            - name: Run tests
              run: cargo test --features "bevy/dynamic_linking" --verbose
            - name: Pedantic Linting
              run: cargo clippy -- -W clippy::pedantic
            - name: Package Debug Build
              run: |
                  DATE=$(date +%Y-%m-%d)
                  COMMIT_HASH=$(git rev-parse --short "$GITHUB_SHA")
                  zip -r "separated-debug-build-${DATE}-${COMMIT_HASH}.zip" target/debug/
            - name: Upload Debug Build
              uses: actions/upload-artifact@v2
              with:
                  name: Debug Build
                  path: "*.zip"